openapi: "3.0.0"
info:
  title: Blood Onator
  description: A M.E.R.N Stack Based application for blood donation. Author - Archit Badjatya
  version: "3.2.1"
  contact:
    email: "architbadjatya@gmail.com"
    url: "https://badjatya.netlify.app/"
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: "{Protocol}://localhost:{Port}/api/{Version}"
    description: Local version of the API
    variables:
      Protocol:
        enum:
          - http
          - https
        default: http
      Port:
        enum:
          - "5000"
          - "6000"
          - "7000"
          - "8000"
        default: "5000"
      Version:
        enum:
          - v1
          - v2
        default: v1

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  # Login
  /auth/login:
    post:
      tags:
        - Manager Login
      summary: A manager can login, using email and password
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  required: true
                  format: email
                  example: indore@gmail.com
                  minLength: 1
                  maxLength: 50
                  description: Enter the password you have used while signup
                password:
                  type: string
                  required: true
                  format: password
                  example: 1234567
                  min: 7
                  description: Enter the password you have used while signup
      responses:
        200:
          description: success, user successfully logged in also cookie added

  # Manager City Routes
  /manager/cities:
    get:
      tags:
        - Manager City
      summary: A logged in manager of his city can view details about blood available in the city
      responses:
        200:
          description: success, details about city

  # Manager Donation Appointment Route
  /manager/appointments/donations:
    get:
      tags:
        - Manager Donation Appointments
      summary: A logged in manager of his city can view all the donation Appointments
      responses:
        200:
          description: success, list of donation Appointments

  /manager/appointments/donations/{id}:
    get:
      tags:
        - Manager Single Donation Appointment
      summary: A logged in manager of his city can view the single donation Appointment by id
      parameters:
        - name: id
          in: path
          type: string
          required: true
          default: 639d6481e612502aa5b4452f
          description: Enter the id of donation
      responses:
        200:
          description: success, the user appointment details
    patch:
      tags:
        - Manager Update Single Donation Appointment
      summary: A logged in manager of his city can update the single donation Appointment by id
      parameters:
        - name: id
          in: path
          type: string
          required: true
          default: 639d6481e612502aa5b4452f
          description: Enter the id of donation
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - amount
              properties:
                status:
                  type: string
                  required: true
                  enum: ["completed", "cancelled"]
                  description: Enter the status
                amount:
                  type: number
                  required: true
                  description: Enter the amount of blood
      responses:
        200:
          description: success, appointment updated

    # Manager Request Appointment Route
  /manager/appointments/requests:
    get:
      tags:
        - Manager Request Appointments
      summary: A logged in manager of his city can view all the Request Appointments
      responses:
        200:
          description: success, list of Request Appointments

  /manager/appointments/requests/{id}:
    get:
      tags:
        - Manager Single Request Appointment
      summary: A logged in manager of his city can view the single Request Appointment by id
      parameters:
        - name: id
          in: path
          type: string
          required: true
          default: 639d6481e612502aa5b4452f
          description: Enter the id of Request
      responses:
        200:
          description: success, the user appointment details
    patch:
      tags:
        - Manager Update Single Request Appointment
      summary: A logged in manager of his city can update the single Request Appointment by id
      parameters:
        - name: id
          in: path
          type: string
          required: true
          default: 639d6481e612502aa5b4452f
          description: Enter the id of Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - status
                - amount
              properties:
                status:
                  type: string
                  required: true
                  enum: ["completed", "cancelled"]
                  description: Enter the status
                amount:
                  type: number
                  required: true
                  description: Enter the amount of blood
      responses:
        200:
          description: success, appointment updated
